CREATE DATABASE DATATRANSFORMER;
USE DATATRANSFORMER;

CREATE TABLE CUSTOMERS (
    CUSTOMERID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    REGISTRATIONDATE DATE
);

INSERT INTO CUSTOMERS VALUES
(1, 'DEEP', 'GAJERA', 'DEEP.GAJERA@GMAIL.COM', '2022-03-15'),
(2, 'JAY', 'JANE', 'JAY.JANE@GMAIL.COM', '2021-11-02');

CREATE TABLE ORDERS (
    ORDERID INT PRIMARY KEY,
    CUSTOMERID INT,
    ORDERDATE DATE,
    TOTALAMOUNT DECIMAL(10,2),
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID)
);

INSERT INTO ORDERS VALUES
(101, 1, '2023-07-01', 150.50),
(102, 2, '2023-07-03', 200.75);

CREATE TABLE EMPLOYEES (
    EMPLOYEEID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    HIREDATE DATE,
    SALARY DECIMAL(10,2)
);

INSERT INTO EMPLOYEES VALUES
(1, 'DEEP', 'GAJERA', 'SALES', '2020-01-15', 50000),
(2, 'JAY', 'JANE', 'HR', '2021-03-20', 55000);

SELECT O.ORDERID, O.ORDERDATE, O.TOTALAMOUNT,
       C.FIRSTNAME, C.LASTNAME
FROM ORDERS O
INNER JOIN CUSTOMERS C 
ON O.CUSTOMERID = C.CUSTOMERID;

SELECT C.*, O.ORDERID, O.TOTALAMOUNT
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.*, C.FIRSTNAME, C.LASTNAME
FROM ORDERS O
RIGHT JOIN CUSTOMERS C
ON O.CUSTOMERID = C.CUSTOMERID;

SELECT * FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
UNION
SELECT * FROM CUSTOMERS C
RIGHT JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID;

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERID IN (
    SELECT CUSTOMERID
    FROM ORDERS
    WHERE TOTALAMOUNT > (SELECT AVG(TOTALAMOUNT) FROM ORDERS)
);

SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT ORDERID,
       YEAR(ORDERDATE) AS ORDERYEAR,
       MONTH(ORDERDATE) AS ORDERMONTH
FROM ORDERS;

SELECT ORDERID,
       DATEDIFF(CURDATE(), ORDERDATE) AS DAYSPASSED
FROM ORDERS;

SELECT ORDERID,
       DATE_FORMAT(ORDERDATE, '%D-%B-%Y') AS FORMATTEDDATE
FROM ORDERS;

SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS FULLNAME
FROM CUSTOMERS;

SELECT REPLACE(FIRSTNAME, 'DEEP', 'DEPASH')
FROM CUSTOMERS;

SELECT TRIM(EMAIL) FROM CUSTOMERS;

SELECT 
    ORDERID, 
    TOTALAMOUNT,
    SUM(TOTALAMOUNT) OVER (ORDER BY ORDERID) AS RUNNINGTOTAL
FROM ORDERS;

SELECT 
    ORDERID, 
    TOTALAMOUNT,
    RANK() OVER (ORDER BY TOTALAMOUNT DESC) AS ORDERRANK
FROM ORDERS;

SELECT ORDERID, TOTALAMOUNT,
       CASE 
          WHEN TOTALAMOUNT > 1000 THEN '10% OFF'
          WHEN TOTALAMOUNT > 500 THEN '5% OFF'
          ELSE 'NO DISCOUNT'
       END AS DISCOUNT
FROM ORDERS;

SELECT FIRSTNAME, SALARY,
       CASE
           WHEN SALARY > 60000 THEN 'HIGH'
           WHEN SALARY >= 40000 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS CATEGORY
FROM EMPLOYEES;
